# Generated by Django 5.2.17 on 2026-10-03 19:35

import django.db.models.deletion
import django.utils.timezone
import recognition.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=recognition.models.original_path)),
                ('processed_image', models.ImageField(blank=True, upload_to=recognition.models.processed_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('outcome', models.CharField(blank=True, choices=[('success', 'Success'), ('no_plate_detected', 'No Plate Detected'), ('unreadable', 'Unreadable'), ('invalid_image', 'Invalid Image')], max_length=20)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('model_version', models.CharField(blank=True, max_length=100)),
                ('error', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='captures', to='recognition.camera')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_plate', models.CharField(db_index=True, max_length=30)),
                ('detector_conf', models.FloatField()),
                ('ocr_conf', models.FloatField()),
                ('bbox', models.JSONField()),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plates', to='recognition.capture')),
            ],
        ),
        migrations.AddIndex(
            model_name='capture',
            index=models.Index(fields=['camera', '-captured_at'], name='recognition_camera__a43caf_idx'),
        ),
        migrations.AddIndex(
            model_name='capture',
            index=models.Index(fields=['status', '-created_at'], name='recognition_status_e8f06f_idx'),
        ),
    ]
