# Generated by Django 5.2.17 on 2026-10-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='raw_text',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='plate',
            name='status',
            field=models.CharField(choices=[('ok', 'Ok'), ('invalid_format', 'Invalid Format'), ('low_confidence', 'Low Confidence'), ('unreadable', 'Unreadable')], default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='capture',
            name='outcome',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('invalid_format', 'Invalid Format'), ('low_confidence', 'Low Confidence'), ('unreadable', 'Unreadable'), ('no_plate_detected', 'No Plate Detected'), ('invalid_image', 'Invalid Image')], max_length=20),
        ),
    ]
