# Generated by Django 5.2.17 on 2026-10-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0002_plate_raw_text_plate_status_alter_capture_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='capture',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capture',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
