# Generated by Django 5.2.17 on 2026-10-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0003_capture_attempts_capture_locked_at_capture_queued_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='image_purged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capture',
            name='purge_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
